format = """\
[\\[](fg:blue)[$time](fg:red)[\\]](fg:blue)\
[\\[](fg:blue)[$username@$hostname:$directory](fg:red)[\\]](fg:blue)\
([\\[](fg:blue)[$git_branch$git_commit:${custom.git_dir}$git_state$git_status](fg:green)[\\]](fg:blue))\
[$cmd_duration](fg:yellow)\
[$jobs](fg:yellow)\
[$status](fg:red)\
[$character](fg:green)\
"""

add_newline = false

[time]
disabled = false
format = '$time'
time_format = "%H:%M"

[username]
format = "$user"
show_always = true

[hostname]
format = "@$hostname"
ssh_only = false

[directory]
format = '$path'
truncation_length = 0

[custom.git_dir]
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
format = '\($output\)'
command = 'basename "$(git rev-parse --show-toplevel 2>/dev/null)"'

[git_branch]
format = '\($symbol$branch\)'
symbol = " "

[git_commit]
format = '\($hash\)'
commit_hash_length = 7
only_detached = false

[git_state]
format = '\($state( $progress_current/$progress_total)\)'

[git_status]
format = '\($all_status$ahead_behind\)'

[jobs]
format = '[$symbol$number]($style)'
symbol = '✦'
threshold = 1

[cmd_duration]
min_time = 2_000
format = '[⏱ $duration]($style)'

[status]
disabled = false
format = '[✗ $status]($style)'

[character]
success_symbol = '\$'
error_symbol = '\$'
